#!/bin/bash

warn()
{
  printf '%s\n' "$@" >&2
}
die()
{
	local state="$?"
	warn "$@"
	exit "$state"
}
usage()
{
	cat <<EOF

./portScan [IP/mask] [PORT]

		-- IP  e.g  88.123.33.87
		-- mask e.g /24  or  /23
		-- PORT 22,110,3306 ... etc

		Example 1: ./portScan 88.123.33.0/24 22,80,3306,6667
		Example 2: ./portScan 88.123.33.24 
		Example 3: ./portScan 88.123.33.24 22	

EOF
}

(( EUID == 0 )) || die "You must be root"

ipAddr=$1
port=$2
args=2
if (( $# < args )); then 
		usage
	else 
	     while read 
                  do
                    nmap -sS "$ipAddr" -p "$port"
             done < <(nmap -sP "$ipAddr" | awk '/Nmap scan/{print $6}' | sed 's|(\([^)]*\))|\1|')
	
fi
